name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
    - uses: actions/checkout@v3

    - name: Install pkg
      run: npm install -g pkg

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        chmod +x generate_formula.sh  # Make the script executable
        chmod +x publish-releases.sh  # Make the script executable
        chmod +x generate_formula.sh  # Make the script executable
        npm install
        npm run build:webpack     # Generate build
        npm run package           # Generate package sh executable file
        npm run tar               # Generate zip file for brew publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/tar
        tag_name: v1.0.0  # Specify the release tag name
        release_name: Release v1.0.0  # Specify the release name
        title: Release v1.0.0  # Specify the release title
        body: Release notes for v1.0.0  # Specify release notes
      env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
